version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/webapp" # Location of package manifests
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "@tauri-apps/api"
        versions: ">=1.5.4"
    groups:
      npm:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/backend" # Location of package manifests
    schedule:
      interval: "monthly"
    groups:
      npm:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/website" # Location of package manifests
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "@tauri-apps/api"
        versions: ">=1.5.4"
    groups:
      npm:
        applies-to: version-updates
        patterns:
          - "*"
