version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/webapp"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "@tauri-apps/api"
        versions: ">=1.5.4"
      - dependency-name: "@tauri-apps/cli"
        versions: ">=2.1.1"
      - dependency-name: "tauri-plugin-log-api"
        versions: "*"
    groups:
      webapp-dependencies:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: "maven"
    directory: "/backend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    groups:
      backend-dependencies:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "@tauri-apps/api"
        versions: ">=1.5.4"
    groups:
      website-dependencies:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/webapp/src-tauri"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    groups:
      tauri-dependencies:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - "*"
