version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/frontend" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/backend" # Location of package manifests
    schedule:
      interval: "weekly"

