files:
  - source: /webapp/src/assets/locales/fr.json
    translation: /webapp/src/assets/locales/%two_letters_code%.json
  - source: /website/src/assets/locales/fr.json
    translation: /website/src/assets/locales/%two_letters_code%.json
