version: '3.4'
services:

  postgres-app:
    image: postgres:14.2-alpine
    container_name: betterfleet-postgres-app
    ports:
      - "2600:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./psql-data/app:/var/lib/postgresql/betterfleet/data/pgdata
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: BetterFleet
      PGDATA: /var/lib/postgresql/betterfleet/data/pgdata
    restart: unless-stopped

  backend:
    image: zelytra/better-fleet-backend:latest
    container_name: betterfleet-backend
    depends_on:
      - postgres-app
    ports:
      - "2601:8080"
    environment:
      DB_HOST: postgres-app
      DB_DATABASE: BetterFleet
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped

  frontend:
    image: zelytra/better-fleet-website:latest
    container_name: betterfleet-website
    depends_on:
      - postgres-app
      - backend
    ports:
      - "2602:80"
    environment:
      VITE_BACKEND_HOST: ${PUBLIC_QUARKUS_HOSTNAME}
    restart: unless-stopped