{{- if not .Values.secrets.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "betterfleet.secretName" . }}
  labels:
    {{- include "betterfleet.labels" (dict "root" $ "component" "secrets") | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  KEYCLOAK_ADMIN: {{ .Values.secrets.keycloakAdminUser | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.secrets.keycloakAdminPassword | quote }}
  MICROSOFT_CLIENT_ID: {{ .Values.secrets.microsoftClientId | quote }}
  MICROSOFT_CLIENT_SECRET: {{ .Values.secrets.microsoftClientSecret | quote }}
  PROXY_CHECK_API_KEY: {{ .Values.secrets.proxyCheckApiKey | quote }}
{{- end }}
